
DANDY_WS_PORT = 7872
MAX_RESOLUTION = 12800
WIDTH_HEIGHT_INPUT = ('INT', {'default': 512, 'min': 10, 'max': MAX_RESOLUTION, 'step': 128})
NEVER_CHANGE = 'never change'.encode().hex()
DANDY_CATEGORY = 'Dandy'

DIRTY_NAME = 'dandy_dirty'
DIRTY_TYPE = 'DANDY_DIRTY'
DIRTY_TYPE_INPUT = (DIRTY_TYPE,)

URL_NAME = 'url'
URL_TYPE = 'DANDY_URLS'
URL_TYPE_INPUT = (URL_TYPE,)

JS_NAME = 'js'
JS_TYPE = 'DANDY_JS_URLS'
JS_TYPE_INPUT = (JS_TYPE,)

HTML_NAME = 'html'
HTML_TYPE = 'DANDY_HTML_URLS'
HTML_TYPE_INPUT = (HTML_TYPE,)

CSS_NAME = 'css'
CSS_TYPE = 'DANDY_CSS_URLS'
CSS_TYPE_INPUT = (CSS_TYPE,)

JSON_NAME = 'json'
JSON_TYPE = 'DANDY_JSON_URLS'
JSON_TYPE_INPUT = (JSON_TYPE,)

YAML_NAME = 'yaml'
YAML_TYPE = 'DANDY_YAML_URLS'
YAML_TYPE_INPUT = (YAML_TYPE,)

WASM_NAME = 'wasm'
WASM_TYPE = 'DANDY_WASM_URLS'
WASM_TYPE_INPUT = (WASM_TYPE,)

CAPTURE_NAME = 'captures'
CAPTURE_TYPE = 'DANDY_CAPTURE'
CAPTURE_TYPE_INPUT = (CAPTURE_TYPE,)

B64IMAGES_NAME = 'b64images'
B64IMAGES_TYPE = 'DANDY_B64IMAGES'
B64IMAGES_TYPE_INPUT = (B64IMAGES_TYPE,)

B64MASKS_NAME = 'b64masks'
B64MASKS_TYPE = 'DANDY_B64MASKS'
B64MASKS_TYPE_INPUT = (B64MASKS_TYPE,)

def DandyWidgets(o):
  return { 'required': {}, 'hidden': {}, 'optional': o }

