
MAX_DANDY_SOCKET_MSG = 2000*1024*1024 # two gigabytes
DANDY_WS_PORT = 7872
MAX_RESOLUTION = 12800
WIDTH_HEIGHT_INPUT = ('INT', {'default': 512, 'min': 10, 'max': MAX_RESOLUTION, 'step': 128})
NEVER_CHANGE = 'never change'.encode().hex()
DANDY_CATEGORY = 'Dandy'

HASH_NAME = 'hash'
HASH_TYPE = 'DANDY_HASH'
HASH_TYPE_INPUT = (HASH_TYPE,)

SERVICE_ID_NAME = 'service_id'
SERVICE_ID_TYPE = 'DANDY_SERVICE_ID'
SERVICE_ID_TYPE_INPUT = (SERVICE_ID_TYPE,)

DIRTY_NAME = 'dandy_dirty'
DIRTY_TYPE = 'DANDY_DIRTY'
DIRTY_TYPE_INPUT = (DIRTY_TYPE,)

URL_NAME = 'url'
URL_TYPE = 'DANDY_URLS'
URL_TYPE_INPUT = (URL_TYPE,)

JS_NAME = 'js'
JS_TYPE = 'DANDY_JS_URLS'
JS_TYPE_INPUT = (JS_TYPE,)

HTML_NAME = 'html'
HTML_TYPE = 'DANDY_HTML_URLS'
HTML_TYPE_INPUT = (HTML_TYPE,)

CSS_NAME = 'css'
CSS_TYPE = 'DANDY_CSS_URLS'
CSS_TYPE_INPUT = (CSS_TYPE,)

JSON_NAME = 'json'
JSON_TYPE = 'DANDY_JSON_URLS'
JSON_TYPE_INPUT = (JSON_TYPE,)

YAML_NAME = 'yaml'
YAML_TYPE = 'DANDY_YAML_URLS'
YAML_TYPE_INPUT = (YAML_TYPE,)

WASM_NAME = 'wasm'
WASM_TYPE = 'DANDY_WASM_URLS'
WASM_TYPE_INPUT = (WASM_TYPE,)

IMAGE_URL_NAME = 'image_url'
IMAGE_URL_TYPE = 'DANDY_IMAGE_URL'
IMAGE_URL_TYPE_INPUT = (IMAGE_URL_TYPE,)

def DandyWidgets(o):
  return { 'required': {}, 'hidden': {}, 'optional': o }
